/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Madi Abio Portfolio
 * My portfolio containing information and my leetcode statistics.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateLeetcodeSolveDto
} from '../generated.schemas';





export type getLeetcodeSolveByIdResponse404 = {
  data: void
  status: 404
}

;
export type getLeetcodeSolveByIdResponseError = (getLeetcodeSolveByIdResponse404) & {
  headers: Headers;
};

export type getLeetcodeSolveByIdResponse = (getLeetcodeSolveByIdResponseError)

export const getGetLeetcodeSolveByIdUrl = (id: number,) => {


  

  return `/leetcode-solves/${id}`
}

export const getLeetcodeSolveById = async (id: number, options?: RequestInit): Promise<getLeetcodeSolveByIdResponse> => {
  
  const res = await fetch(getGetLeetcodeSolveByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getLeetcodeSolveByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getLeetcodeSolveByIdResponse
}
  




export const getGetLeetcodeSolveByIdQueryKey = (id: number,) => {
    return [
    `/leetcode-solves/${id}`
    ] as const;
    }

    
export const getGetLeetcodeSolveByIdQueryOptions = <TData = Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLeetcodeSolveByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeetcodeSolveById>>> = ({ signal }) => getLeetcodeSolveById(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLeetcodeSolveByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLeetcodeSolveById>>>
export type GetLeetcodeSolveByIdQueryError = void


export function useGetLeetcodeSolveById<TData = Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeetcodeSolveById>>,
          TError,
          Awaited<ReturnType<typeof getLeetcodeSolveById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLeetcodeSolveById<TData = Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeetcodeSolveById>>,
          TError,
          Awaited<ReturnType<typeof getLeetcodeSolveById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLeetcodeSolveById<TData = Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLeetcodeSolveById<TData = Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeetcodeSolveById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLeetcodeSolveByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type createResponse201 = {
  data: void
  status: 201
}

export type createResponseSuccess = (createResponse201) & {
  headers: Headers;
};
;

export type createResponse = (createResponseSuccess)

export const getCreateUrl = () => {


  

  return `/leetcode-solves`
}

export const create = async (createLeetcodeSolveDto: CreateLeetcodeSolveDto, options?: RequestInit): Promise<createResponse> => {
  
  const res = await fetch(getCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLeetcodeSolveDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createResponse
}
  



export const getCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateLeetcodeSolveDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateLeetcodeSolveDto}, TContext> => {

const mutationKey = ['create'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create>>, {data: CreateLeetcodeSolveDto}> = (props) => {
          const {data} = props ?? {};

          return  create(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>
    export type CreateMutationBody = CreateLeetcodeSolveDto
    export type CreateMutationError = unknown

    export const useCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateLeetcodeSolveDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create>>,
        TError,
        {data: CreateLeetcodeSolveDto},
        TContext
      > => {
      return useMutation(getCreateMutationOptions(options), queryClient);
    }
    